name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Testing key
        env:
        SUPER_SECRET: ${{ secrets.TEST_KEY }}
        run: echo "$SUPER_SECRET"
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY : ${{ secrets.SSH_KEY }}
          REMOTE_HOST: "ec2-3-96-193-149.ca-central-1.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/kijiji_clone"